### ISSUE TITLE
Blob Store is not created during Repository creation

### ISSUE THREAD

**Issue by couchuser12345** [wandenberg/puppet-module-nexus3_rest#14]
When I configure the nexus3_repository, I am adding a `blobstore_name => 'my_blob_name'`, however it seems to revert to the 'default' blob if this blobname does not exist already.

Should the definition of this repostiory not create the blobstore if it does not already exists?
Or should there be a nexus3_blobstore functionality added to support managing blobstores to allow for this?

**Comment by couchuser12345** [comment]
Thinking about this more, in my case I was expected a new blob to be created using the type "File" and expecting nexus3 to manage creation of a default path, but since blobs can also be stored in S3 buckets, it would seem that it would be best to support a nexus3_blobstore management interface.

**Comment by wandenberg** [comment]
Just released version 0.3.0 with support to manage blobstore including S3
