### ISSUE TITLE
Support for cleanup policies

### ISSUE THREAD

**Issue by dhs-rec** [wandenberg/puppet-module-nexus3_rest#16]
Latest Nexus releases have added support for s.c. **Cleanup Policies**, which can be attached to repositories to do automated cleanups. This is esp. useful for proxy repos, for example to remove all artifacts that haven't been downloaded since X days. This is way simpler than writing custom scripts for this.

Would be great if one could manage the cleanup policies with Puppet, too.

**Comment by dhs-rec** [comment]
Knock, knock. Anybody here?

**Comment by wandenberg** [comment]
Hi @dhs-rec . Yes, there is somebody here. :)
I saw your request, will be done when possible. The idea is to cover all the configurations, but map the Nexus API isn't an easy task due to the lack of documentation.
Feel free to submit a pull request.
