### ISSUE TITLE
nexus3_repository always checks "HTTP -> Authentication"

### ISSUE THREAD

**Issue by dhs-rec** [wandenberg/puppet-module-nexus3_rest#18]
When managing repositories with `nexus3_repository` the resulting repositories always have "HTTP -> Authentication" checked.

When reading the configuration using a Groovy script, I get this:
`[..., 'httpclient':['blocked':false, 'autoBlock':true, 'authentication':[:]], ...]`
But after manually unchecking the option, a subsequent run of the script yields this:
`[..., 'httpclient':['blocked':false, 'autoBlock':true], ...]`

My guess is that it comes from these lines in `create_config.erb`:
```
<%- if resource[:remote_auth_type] == :none -%>
config.getAttributes().remove('httpclient')
<%- else -%>
```
I think it should remove `httpclient['authentication']` instead.

Script:
```
def repositories = repository.repositoryManager.browse()
repositories.findResults { repository ->
  def config = repository.getConfiguration()
  log.info(config.repositoryName + '(' + config.recipeName + '): ' + config.getAttributes().inspect())
}
```

**Comment by dhs-rec** [comment]
Maybe something like this would fix that:
```
def httpclient = config.attributes('httpclient');
<%- if resource[:remote_auth_type] == :none -%>
httpclient.remove('authentication')
<%- else -%>
def authentication = httpclient.child('authentication');
authentication.set('type', '<%= resource[:remote_auth_type] %>');
authentication.set('username', '<%= resource[:remote_user] %>');
authentication.set('password', '<%= resource[:remote_password] %>');
authentication.set('ntlmHost', '<%= resource[:remote_ntlm_host] %>');
authentication.set('ntlmDomain', '<%= resource[:remote_ntlm_domain] %>');
<%- end -%>
```
This could also enable handling of the `blocked` and `autoBlock` attributes above (if the type is enhanced accordingly), by adding something like
```
httpclient.set('blocked', '<%= resource[:blocked] %>');
httpclient.set('autoBlock', '<%= resource[:auto_block] %>');
```

**Comment by wandenberg** [comment]
Hi @dhs-rec, please test your suggestions and open a merge request when it is working.
I will be happy to accept the changes.
As far as I noticed, even though the checkbox is flagged the Nexus does not really require the authentication.
