### ISSUE TITLE
nexus 3 is running on https

### ISSUE THREAD

**Issue by shawnxue** [wandenberg/puppet-module-nexus3_rest#2]
Hi,

My nexus 3 is running in https protocol (incoming SSL is configured by jetty https). Does this module support that? If so, what nexus_base_url should I use in /etc/puppet/nexus_rest.conf, such as https://localhost:8443/?

Thanks

Shawn

**Comment by wandenberg** [comment]
Hi @shawnxue, for the delay.
The configuration depends on how your nexus is configured to accept connections.
Probably `https://localhost` will be enough or use the DNS you used on your certificate.
Let me know if you still need help on this or if I can close the issue.
