### ISSUE TITLE
nexus3_repository: Could not run the command due to '400'

### ISSUE THREAD

**Issue by yenda23** [wandenberg/puppet-module-nexus3_rest#25]
When I use Nexus v > 2.19, I cannot create repository with puppet, agent is throwing errors like this:
<pre>
Error: Error while creating nexus3_repository npm-proxy: Could not run the command due to '400' '{
  "name" : "10615bc812fcb765a2eea63ec8475aa1",
  "result" : "org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:\nScript8.groovy: 1: You cannot create an instance from the abstract interface 'org.sonatype.nexus.repository.config.Configuration'.\n @ line 1, column 14.\n   def config = new org.sonatype.nexus.repository.config.Configuration()\n                ^\n\n1 error\n"
}'
Error: /Stage[main]/Profile_nexus::Config/Nexus3_repository[npm-proxy]/ensure: change from 'absent' to 'present' failed: Error while creating nexus3_repository npm-proxy: Could not run the command due to '400' '{
  "name" : "10615bc812fcb765a2eea63ec8475aa1",
  "result" : "org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:\nScript8.groovy: 1: You cannot create an instance from the abstract interface 'org.sonatype.nexus.repository.config.Configuration'.\n @ line 1, column 14.\n   def config = new org.sonatype.nexus.repository.config.Configuration()\n                ^\n\n1 error\n"
}'
</pre>

**Comment by wandenberg** [comment]
Hi @yenda23 did you mean > 3.19, right? This module does not support Nexus 2 version

**Comment by wandenberg** [comment]
I have just released some fixes to make the module support Nexus 3.20+ if this is the case.
