### ISSUE TITLE
Request for "preemptive bearer token" auhentication support for (npm) proxy repos

### ISSUE THREAD

**Issue by jhooyberghs** [wandenberg/puppet-module-nexus3_rest#33]
We ran into an issue where an upstream NPM repo we want to proxy through nexus, needs the "preemptive bearer token" authentication added in Nexus OSS 3.20 (Source: https://help.sonatype.com/repomanager3/release-notes/2019-release-notes#id-2019ReleaseNotes-Enhancednpmloginforprivaterepositoryusages), released at the end of 2019.

For now we downloaded the packages we needed and put them in a (temporary) hosted npm repo as a fast workaround.

We'll see if we can add this ourself in the near future through a PR, of wait for someone else to pick to up in the meanwhile.

**Comment by wandenberg** [comment]
added on ec49e17d075b96d0aaa3e643b29d560439612ba1
