### ISSUE TITLE
Add support for Negative Cache configuration

### ISSUE THREAD

**Issue by prisma2user** [wandenberg/puppet-module-nexus3_rest#34]
Within Nexus proxied repositories, nexus supports configuration for a negative cache which essentially allows nexus to cache objects it doesnt find on the upstream proxied repository so that it doesnt keep re-requesting this if it doesnt exist upstream.

The supported options are:
- Not Found Cache Enabled / Disabled | enables not found cache
- Not Found Cache TTL (time to live) | Time to cache the not found objects

**Comment by wandenberg** [comment]
added on d6511802fe4b3e2e88270c2a3c59113f93e90930
