### ISSUE TITLE
Add support for 'r' and 'go' format

### ISSUE THREAD

**Issue by GopalGupta1805** [wandenberg/puppet-module-nexus3_rest#37]
Within Nexus repositories, nexus supports configuration for r (group, hosted, proxy) and go (group, proxy). It will be good to have these supports.

**Comment by wandenberg** [comment]
Done on commits 06a40189f3505d833987f68f9699f230a612fb7f and a9ab14aeca9fb970021ab4a98a44a8e549ef5bdd
