### ISSUE TITLE
Maven2 hosted: "remote_auth_type changed 'none' to 'username' (corrective)" on every agent run

### ISSUE THREAD

**Issue by dhs-rec** [wandenberg/puppet-module-nexus3_rest#40]
After adding management for some **hosted** Maven2 repositories to my setup, I found that the agent always corrected the `remote_auth_type` setting from `none` to `username`.

The reason for this is the `defaultto` setting for `remote_auth_type` specified in the type, which is not restricted to proxy repositories.

**Comment by wandenberg** [comment]
Done on commit 06a40189f3505d833987f68f9699f230a612fb7f
