### ISSUE TITLE
After update to 1.0.0 always updates version policy of M2 group repos

### ISSUE THREAD

**Issue by dhs-rec** [wandenberg/puppet-module-nexus3_rest#49]
Since updating to 1.0.0, the version policy of every Maven2 group repository is updated from empty to given value on every Puppet agent run:
```
Notice: /Stage[main]/Nexus::Groups/Nexus3_repository_group[my-repo-group]/version_policy: version_policy changed '' to 'mixed' (corrective)
```
and I also get a warning like this one:
```
Warning: nexus3_repository_group[my-repo-group]#get has not provided canonicalized values.
```
 I checked with the REST API and I don't get a `versionPolicy` field back for Maven2 group repositories, for example:

Querying https://our.nexus.server/service/rest/v1/repositories/maven/group/my-repo-group returns
```
{
  "name": "my-repo-group",
  "format": "maven2",
  "url": "https://our.nexus.server/repository/my-repo-group",
  "online": true,
  "storage": {
    "blobStoreName": "default",
    "strictContentTypeValidation": true
  },
  "group": {
    "memberNames": [
      "member1",
      "member2"
    ]
  },
  "type": "group"
}
```
and I guess the same is true for the script API. This means the `versionPolicy` field is always empty (as set by the `read_config.erb` script template, line 36) and thus Puppet never get's the actual value to compare with.

**Comment by wandenberg** [comment]
@dhs-rec which version of Nexus are you using?
Both issues are probably related to this.
I will probably need to change something to support old versions since version 1.0.0 was built on top of the Nexus version 3.40.1.

**Comment by dhs-rec** [comment]
It's 3.40.1.

**Comment by wandenberg** [comment]
Weird. Do you mind sending me a print screen of the configuration of the repository on the Nexus online system, and your puppet definition for it?
Then I can reproduce it here.

**Comment by dhs-rec** [comment]
I've created a simple Ruby script to upload and execute the read_config script (as resulting from resolving the template) for group repos and found that some of my M2 group repositories had indeed a non-empty `version_policy` in the resulting JSON, while others had not. Just like in #50, manual saving of the repository configuration in Nexus changed the string from empty to the correct content. However, changing version policy after repository creation is not supported in Nexus, so other values than the current one will result in Puppet trying again and again...
