### ISSUE TITLE
Internal server error when downloading from NPM repositories after update to 1.0.0

### ISSUE THREAD

**Issue by dhs-rec** [wandenberg/puppet-module-nexus3_rest#50]
After updating the module to 1.0.0, the first Puppet run has changed the configuration of NPM repositories:
```
Notice: /Stage[main]/Nexus::Repositories::Npm/Nexus3_repository[my-npm-proxy]/remove_non_cataloged: remove_non_cataloged changed '' to 'false'
Notice: /Stage[main]/Nexus::Repositories::Npm/Nexus3_repository[my-npm-proxy]/remove_quarantined_versions: remove_quarantined_versions changed '' to 'false'
```
which resulted in an "Internal Server Error (500)" when downloading from an NPM repository:
```
java.lang.ClassCastException: Cannot cast java.lang.String to java.lang.Boolean
        at java.lang.Class.cast(Class.java:3369)
```
that I fixed by manually saving the configuration of affected NPM repos once.

I assume this should be `false` (Boolean) instead of `'false'` (String)...

**Comment by dhs-rec** [comment]
The internal server error returns every time the configuration for an NPM proxy changes (and, of course, if a new NPM proxy is created), which needs a manual saving of the configuration to fix it.

**Comment by wandenberg** [comment]
@dhs-rec can you give a try on the branch `fixes_for_1.0.1`?

**Comment by dhs-rec** [comment]
Yes, that looks better. Created another NPM proxy and could fetch artifacts from it right away w/o having to manually save its configuration beforehand in order to avoid an interanl server error. Thanks a lot.
