### ISSUE TITLE
Cleanup_policies idempotency

### ISSUE THREAD

**Issue by Joris29** [wandenberg/puppet-module-nexus3_rest#55]
While using the cleanup_policies for repositories I'm getting strange errors.
Puppet version: 7.21.0
Nexus version: OSS 3.43.0-01

1. When a cleanup policy is manually added it should put it back on empty but it keeps changing.
![image](https://user-images.githubusercontent.com/25951077/215416076-1aa7a507-3998-4ff8-bc61-54bf3d0b74ee.png)

2. When adding multiple policies i also keep getting a change and a strange error
![image](https://user-images.githubusercontent.com/25951077/215416452-6358c288-86fc-4dc9-a6ee-781cc0b2a523.png)

**Comment by fdammeke** [comment]
Facing the same issue here.
