### ISSUE TITLE
RealmManager MissingMethodException 

### ISSUE THREAD

**Issue by brianmhowell** [wandenberg/puppet-module-nexus3_rest#61]
```
Sonatype Nexus OSS: 3.60.0-02
nexus3_rest: 1.0.3
 ``` 
I've defined active realms as:

 ```
nexus3_realm_settings { 'global':
    names => ['LdapRealm','NexusAuthenticatingRealm'],
  }
```

1. `NexusAuthorizingRealm` [was removed](https://help.sonatype.com/en/sonatype-nexus-repository-3-60-0-release-notes.html#removed-local-authorizing-realm-from-user-interface-and-api) from the UI and API in version `3.60.0-02` making it a protected default
2. `getConfiguration()` is no longer a public method of `RealmManagerImpl`, as of Nexus `3.60.0-02`

When I run against my current Nexus installation I get a puppet error:
```
Could not evaluate: Error while retrieving configuration: Could not run the command due to '400' '{
"name" : "900ee3129e702a2c20f413050e2fa8e7",
"result" : "javax.script.ScriptException: groovy.lang.MissingMethodException: No signature of method: org.sonatype.nexus.security.internal.RealmManagerImpl$$EnhancerByGuice$$78451718.getConfiguration() is applicable for argument types: () values: []"
}'
```
Reference: https://javadoc.io/doc/org.sonatype.nexus/nexus-security/3.60.0-02/org/sonatype/nexus/security/internal/RealmManagerImpl.html

**Comment by dhs-rec** [comment]
Running into this as well after updating Nexus from 3.51 to 3.66. Maybe it's about time to migrate the module from script API to REST API...
