### ISSUE TITLE
Add support for PRO version of Nexus

### ISSUE THREAD

**Issue by brianmhowell** [wandenberg/puppet-module-nexus3_rest#64]
wandenberg/nexus3_rest only supports OSS version of Nexus, not PRO (licensed) version

from [api.rb](https://github.com/wandenberg/puppet-module-nexus3_rest/blob/master/lib/puppet_x/nexus3/api.rb)
```
def self.version
    @version ||= nexus3_server_version
end

def self.nexus3_server_version
    result = execute_script('return container.lookup(com.sonatype.nexus.edition.oss.ApplicationVersionImpl.class.name).getVersion()')
    result.split('.')[0..1].join('.').to_f
  rescue
    3.19
end
```

this code should *also* check `result = execute_script('return container.lookup(com.sonatype.nexus.edition.pro.ApplicationVersionImpl.class.name).getVersion()')`

**Comment by wandenberg** [comment]
@brianmhowell I don't have a license for the PRO version :( 
Could you make the code changes and submit a merge request? (or temporarily give me access to your server)

**Comment by brianmhowell** [comment]
Are there any plans to release this fix? A 1.0.4 or a 2.0.0 version
perhaps? I see that [Fix #64
<https://github.com/wandenberg/puppet-module-nexus3_rest/issues/64> adding
support to PRO version] belongs to a fork and not the project proper?

**Comment by wandenberg** [comment]
done. 1.0.4 released

**Comment by brianmhowell** [comment]
oh my gosh ... you are awesome and timely!!
