### ISSUE TITLE
admin.password file gets created even if password for admin is specified

### ISSUE THREAD

**Issue by thomasminst** [wandenberg/puppet-module-nexus3_rest#67]
When provisioning a server, the "nexus::config::admin::password" is set and Nexus uses it, so everything looks good.
But even when the password has a value, the file /opt/sonatype/sonatype-work/nexus3/admin.password gets created and next time Puppet runs it throws an authentication error. As per the documentation, that random password should only be created if the admin password is not defined.
I tried deleting the file but it gets created every time Puppet runs (when nexus restarts), also, if I try to set it to absent I get a dependency cycle error.

nexus version: 3.71.0.06 (It seems that this issue was introduced in this version (no issues in the previous version 3.69.0.02).

**Comment by dhs-rec** [comment]
This isn't an issue with this module, but with Nexus itself. I see this in `nexus.log` since 3.70.x after Nexus updates:
```
2024-09-10 12:56:24,553+0200 INFO  [FelixStartLevel]  *SYSTEM org.sonatype.nexus.security.internal.AdminPasswordFileManagerImpl - Writing admin user temporary password to /opt/sonatype/sonatype-work/nexus3/admin.password
```
See also: https://github.com/sonatype/nexus-public/issues/458

**Comment by thomasminst** [comment]
Indeed. It's an issue in the package it seems. Can be closed.
